In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Waterbase_v2018_1_WISE4_csv/Waterbase_v2018_1_T_WISE4_BiologyEQRData.csv")

In [3]:
data.head()

,monitoringSiteIdentifier,monitoringSiteIdentifierScheme,parameterWaterBodyCategory,parameterNCSWaterBodyType,observedPropertyDeterminandBiologyEQRCode,phenomenonTimeReferenceYear,parameterSamplingPeriod,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,resultObservationStatus,Remarks,metadata_versionId,metadata_beginLifeSpanVersion,metadata_statusCode,metadata_observationStatus,metadata_statements,UID
0,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_123-01-3,2010,2010-06--2010-08,345,1,0.509,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_182: resultNormalisedEQRValue cannot...,24044
1,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_13-01-4,2007,2007-09--2007-11,345,5,0.518,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_182: resultNormalisedEQRValue cannot...,24045
2,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_13-01-4,2010,2010-09--2010-11,345,5,0.373,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_EQR_MISS: Not available resultNormal...,24046
3,NO001-51057,eionetMonitoringSiteCode,RW,REL2321,EEA_124-03-8,2012,2012-01--2012-12,2,1,0.940,0.70,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24047
4,NO001-60117,eionetMonitoringSiteCode,RW,REL2221,EEA_124-03-8,2012,2012-01--2012-12,1,1,1.040,0.98,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24048

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29741 entries, 0 to 29740
Data columns (total 19 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   monitoringSiteIdentifier                   29741 non-null  object
 1   monitoringSiteIdentifierScheme             29741 non-null  object
 2   parameterWaterBodyCategory                 29741 non-null  object
 3   parameterNCSWaterBodyType                  29680 non-null  object
 4   observedPropertyDeterminandBiologyEQRCode  29741 non-null  object
 5   phenomenonTimeReferenceYear                29741 non-null  int64
 6   parameterSamplingPeriod                    27503 non-null  object
 7   resultEcologicalStatusClassValue           29741 non-null  int64
 8   resultNumberOfSamples                      29741 non-null  int64
 9   resultEQRValue                             27425 non-null  float64
 10  resultNormalisedEQRValue                   19714 non-null  float64
 11  resultObservationStatus                    7945 non-null   object
 12  Remarks                                    7064 non-null   object
 13  metadata_versionId                         29741 non-null  object
 14  metadata_beginLifeSpanVersion              29741 non-null  object
 15  metadata_statusCode                        29741 non-null  object
 16  metadata_observationStatus                 29741 non-null  object
 17  metadata_statements                        3319 non-null   object
 18  UID                                        29741 non-null  int64
dtypes: float64(2), int64(4), object(13)
memory usage: 4.3+ MB

In [5]:
data[["resultEcologicalStatusClassValue","resultNumberOfSamples","resultEQRValue","resultNormalisedEQRValue"]]

,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue
0,345,1,0.509000,NaN
1,345,5,0.518000,NaN
2,345,5,0.373000,NaN
3,2,1,0.940000,0.700000
4,1,1,1.040000,0.980000
...,...,...,...,...
29736,4,1,0.226481,NaN
29737,345,1,0.448035,NaN
29738,3,1,0.438366,NaN
29739,2,1,0.648636,0.748636
29740,3,1,0.413922,NaN

In [119]:
data["resultEQRValue"].isna().sum()

2316

In [120]:
data = data[data['resultEQRValue'].notna()]

In [121]:
data.head()

,monitoringSiteIdentifier,monitoringSiteIdentifierScheme,parameterWaterBodyCategory,parameterNCSWaterBodyType,observedPropertyDeterminandBiologyEQRCode,phenomenonTimeReferenceYear,parameterSamplingPeriod,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,resultObservationStatus,Remarks,metadata_versionId,metadata_beginLifeSpanVersion,metadata_statusCode,metadata_observationStatus,metadata_statements,UID
0,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_123-01-3,2010,2010-06--2010-08,345,1,0.509,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_182: resultNormalisedEQRValue cannot...,24044
1,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_13-01-4,2007,2007-09--2007-11,345,5,0.518,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_182: resultNormalisedEQRValue cannot...,24045
2,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_13-01-4,2010,2010-09--2010-11,345,5,0.373,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_EQR_MISS: Not available resultNormal...,24046
3,NO001-51057,eionetMonitoringSiteCode,RW,REL2321,EEA_124-03-8,2012,2012-01--2012-12,2,1,0.940,0.70,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24047
4,NO001-60117,eionetMonitoringSiteCode,RW,REL2221,EEA_124-03-8,2012,2012-01--2012-12,1,1,1.040,0.98,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24048

In [122]:
data.shape

(27425, 19)

In [123]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27425 entries, 0 to 29740
Data columns (total 19 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   monitoringSiteIdentifier                   27425 non-null  object
 1   monitoringSiteIdentifierScheme             27425 non-null  object
 2   parameterWaterBodyCategory                 27425 non-null  object
 3   parameterNCSWaterBodyType                  27377 non-null  object
 4   observedPropertyDeterminandBiologyEQRCode  27425 non-null  object
 5   phenomenonTimeReferenceYear                27425 non-null  int64
 6   parameterSamplingPeriod                    26475 non-null  object
 7   resultEcologicalStatusClassValue           27425 non-null  int64
 8   resultNumberOfSamples                      27425 non-null  int64
 9   resultEQRValue                             27425 non-null  float64
 10  resultNormalisedEQRValue                   18848 non-null  float64
 11  resultObservationStatus                    7790 non-null   object
 12  Remarks                                    5360 non-null   object
 13  metadata_versionId                         27425 non-null  object
 14  metadata_beginLifeSpanVersion              27425 non-null  object
 15  metadata_statusCode                        27425 non-null  object
 16  metadata_observationStatus                 27425 non-null  object
 17  metadata_statements                        2885 non-null   object
 18  UID                                        27425 non-null  int64
dtypes: float64(2), int64(4), object(13)
memory usage: 4.2+ MB

In [124]:
data.head(10)

,monitoringSiteIdentifier,monitoringSiteIdentifierScheme,parameterWaterBodyCategory,parameterNCSWaterBodyType,observedPropertyDeterminandBiologyEQRCode,phenomenonTimeReferenceYear,parameterSamplingPeriod,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,resultObservationStatus,Remarks,metadata_versionId,metadata_beginLifeSpanVersion,metadata_statusCode,metadata_observationStatus,metadata_statements,UID
0,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_123-01-3,2010,2010-06--2010-08,345,1,0.50900,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_182: resultNormalisedEQRValue cannot...,24044
1,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_13-01-4,2007,2007-09--2007-11,345,5,0.51800,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_182: resultNormalisedEQRValue cannot...,24045
2,NL94_OUDMS_A,euMonitoringSiteCode,RW,R8,EEA_13-01-4,2010,2010-09--2010-11,345,5,0.37300,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_EQR_MISS: Not available resultNormal...,24046
3,NO001-51057,eionetMonitoringSiteCode,RW,REL2321,EEA_124-03-8,2012,2012-01--2012-12,2,1,0.94000,0.70,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24047
4,NO001-60117,eionetMonitoringSiteCode,RW,REL2221,EEA_124-03-8,2012,2012-01--2012-12,1,1,1.04000,0.98,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24048
5,NO001-60271,eionetMonitoringSiteCode,RW,REL1321,EEA_124-03-8,2012,2012-01--2012-12,1,1,1.02000,0.94,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24049
6,NO002-252-L,eionetMonitoringSiteCode,LW,LEM22215,EEA_123-04-6,2012,2012-01--2012-12,1,1,1.03719,1.00,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24050
7,NO002-27861,eionetMonitoringSiteCode,RW,REL2321,EEA_124-03-8,2012,2012-01--2012-12,1,1,0.98000,0.83,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24051
8,NO002-28178,eionetMonitoringSiteCode,RW,REL3311,EEA_124-03-8,2012,2012-01--2012-12,2,1,0.91000,0.61,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24052
9,NO002-28730,eionetMonitoringSiteCode,RW,REM1311,EEA_124-03-8,2012,2012-01--2012-12,2,1,0.95000,0.76,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24053

In [125]:
data.value_counts("parameterWaterBodyCategory")[:20]

parameterWaterBodyCategory
RW    23097
LW     4309
TW       12
CW        7
dtype: int64

In [126]:
data["resultEQRValue"].max()

59.0

In [9]:
data[data.resultEQRValue >= 2.0][["resultEQRValue","resultNormalisedEQRValue"]]

       resultEQRValue  resultNormalisedEQRValue
67               2.02                       NaN
69               3.96                       NaN
74               2.43                       NaN
666              3.00                       NaN
667              3.00                       NaN
...               ...                       ...
29498            2.10                       NaN
29567            4.59                       NaN
29590            2.38                       NaN
29665            4.18                       NaN
29708            3.25                       NaN

[182 rows x 2 columns]

In [24]:
data[(data.resultNormalisedEQRValue == 1.0)][["resultEQRValue","resultNormalisedEQRValue"]].describe()

       resultEQRValue  resultNormalisedEQRValue
count     3749.000000                    3773.0
mean         0.936223                       1.0
std          0.270939                       0.0
min          0.000000                       1.0
25%          1.000000                       1.0
50%          1.000000                       1.0
75%          1.071429                       1.0
max          2.000000                       1.0

In [ ]:
data[data.resultNormalisedEQRValue == 1.0][["resultEQRValue","resultNormalisedEQRValue"]].describe()

In [ ]:
data[]

In [6]:
data.describe()

,phenomenonTimeReferenceYear,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,UID
count,29741.000000,29741.000000,29741.000000,27425.000000,19714.000000,29741.000000
mean,2012.130426,13.336875,1.791903,0.805671,0.707798,27945.167143
std,2.432112,61.069266,1.418429,1.665382,0.222220,14435.975046
min,1992.000000,1.000000,1.000000,0.000000,-0.053333,29.000000
25%,2010.000000,1.000000,1.000000,0.554000,0.554286,12240.000000
50%,2012.000000,2.000000,1.000000,0.746000,0.711111,31821.000000
75%,2014.000000,3.000000,2.000000,0.910000,0.900000,39527.000000
max,2017.000000,345.000000,22.000000,59.000000,1.000000,47296.000000

In [128]:
data[data.resultNormalisedEQRValue == 1.0]["resultEQRValue"].max()

2.0

In [129]:
data = data[data.resultEQRValue != 59.0]

In [130]:
data = data[data.resultEQRValue != 57.0]

In [131]:
data = data[data.resultEQRValue != 51.0]

In [132]:
data.describe()

,phenomenonTimeReferenceYear,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,UID
count,27421.000000,27421.000000,27421.000000,27421.000000,18848.000000,27421.000000
mean,2012.050800,14.010795,1.754896,0.797547,0.707950,27685.876919
std,2.466421,62.780417,1.410982,1.523080,0.223777,14768.912905
min,1992.000000,1.000000,1.000000,0.000000,-0.053333,29.000000
25%,2010.000000,1.000000,1.000000,0.554000,0.550000,11733.000000
50%,2012.000000,2.000000,1.000000,0.745455,0.710000,32203.000000
75%,2014.000000,3.000000,2.000000,0.910000,0.900125,39660.000000
max,2017.000000,345.000000,22.000000,50.000000,1.000000,47296.000000

In [25]:
data[data.resultNormalisedEQRValue < 0]

,monitoringSiteIdentifier,monitoringSiteIdentifierScheme,parameterWaterBodyCategory,parameterNCSWaterBodyType,observedPropertyDeterminandBiologyEQRCode,phenomenonTimeReferenceYear,parameterSamplingPeriod,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,resultObservationStatus,Remarks,metadata_versionId,metadata_beginLifeSpanVersion,metadata_statusCode,metadata_observationStatus,metadata_statements,UID
28874,ITR110041AAR,euMonitoringSiteCode,RW,M1,EEA_13-01-4,2012,2012-01--2012-12,4,2,0.207,-0.027500,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,36709
28907,ITR1101406AS,euMonitoringSiteCode,RW,M1,EEA_13-01-4,2012,2012-01--2012-12,4,3,0.176,-0.053333,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,36742

In [133]:
data = data[data.resultEQRValue <= 2.0]

In [134]:
data[data.resultEQRValue >= 1.3]

,monitoringSiteIdentifier,monitoringSiteIdentifierScheme,parameterWaterBodyCategory,parameterNCSWaterBodyType,observedPropertyDeterminandBiologyEQRCode,phenomenonTimeReferenceYear,parameterSamplingPeriod,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,resultObservationStatus,Remarks,metadata_versionId,metadata_beginLifeSpanVersion,metadata_statusCode,metadata_observationStatus,metadata_statements,UID
29,PLSM_PL07S0802_0057,euMonitoringSiteCode,LW,5a,EEA_11-04-1,2011,2011-04--2011-10,2,3,1.460000,NaN,NaN,3 stations within the lake; index value and cl...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_EQR_MISS: Not available resultNormal...,24074
58,PLSM_PL01S0202_2272,euMonitoringSiteCode,LW,3a,EEA_11-04-1,2011,2011-04--2011-10,2,3,1.440000,NaN,NaN,3 stations within the lake; index value and cl...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_EQR_MISS: Not available resultNormal...,24106
64,ES020ESPF004300399,euMonitoringSiteCode,RW,103,EEA_13-04-7,2014,2014-01-01--2014-12-31,1,1,1.466000,NaN,NaN,NaN,http://cdr.eionet.europa.eu/es/eea/wise_soe/wi...,2017-05-23 08:44:05.000,valid,A,NaN,43145
66,PLSM_PL01S0602_0354,euMonitoringSiteCode,LW,3a,EEA_11-04-1,2011,2011-04--2011-10,2,7,1.900000,NaN,NaN,5 stations within the lake; index value and cl...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_181: resultEQRValue was reported in ...,24115
490,FRDR06970900,euMonitoringSiteCode,RW,M5,EEA_13-01-4,2010,2010-09--2010-11,1,1,1.357143,1.0,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,5478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29131,PL01S0602_3011,euMonitoringSiteCode,LW,3b,EEA_11-04-1,2011,2011-04--2011-10,2,3,1.520000,NaN,NaN,2 stations within the lake; index value and cl...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_181: resultEQRValue was reported in ...,37001
29140,PL01S1102_0648,euMonitoringSiteCode,LW,7b,EEA_11-04-1,2011,2011-04--2011-10,2,3,1.870000,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_181: resultEQRValue was reported in ...,37010
29163,PL01S0702_0538,euMonitoringSiteCode,LW,2a,EEA_11-04-1,2011,2011-04--2011-10,2,6,1.880000,NaN,NaN,2 stations within the lake; index value and cl...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_181: resultEQRValue was reported in ...,37033
29418,PL01S0602_3030,euMonitoringSiteCode,LW,3a,EEA_11-04-1,2011,2011-04--2011-10,2,3,1.680000,NaN,NaN,3 stations within the lake; index value and cl...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_181: resultEQRValue was reported in ...,37234
29419,PL02S0502_0182,euMonitoringSiteCode,LW,2a,EEA_11-04-1,2011,2011-04--2011-10,2,8,1.710000,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,U,QC_LEGACY_181: resultEQRValue was reported in ...,37235

In [135]:
data.resultNormalisedEQRValue.max()

1.0

In [136]:
data[data.resultNormalisedEQRValue == 1.0]["resultEQRValue"].max()

2.0

In [137]:
data[data.resultNormalisedEQRValue == 1.0]

,monitoringSiteIdentifier,monitoringSiteIdentifierScheme,parameterWaterBodyCategory,parameterNCSWaterBodyType,observedPropertyDeterminandBiologyEQRCode,phenomenonTimeReferenceYear,parameterSamplingPeriod,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,resultObservationStatus,Remarks,metadata_versionId,metadata_beginLifeSpanVersion,metadata_statusCode,metadata_observationStatus,metadata_statements,UID
6,NO002-252-L,eionetMonitoringSiteCode,LW,LEM22215,EEA_123-04-6,2012,2012-01--2012-12,1,1,1.03719,1.0,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24050
15,NO002-57223,eionetMonitoringSiteCode,RW,REM1211,EEA_124-03-8,2012,2012-01--2012-12,1,1,1.08000,1.0,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24059
40,NO002-58998,eionetMonitoringSiteCode,RW,REL1321,EEA_124-03-8,2012,2012-01--2012-12,1,1,1.10000,1.0,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24088
104,LUL112010A11,euMonitoringSiteCode,RW,3,EEA_13-01-4,2015,2015-06-21--2015-06-22,1,1,1.05900,1.0,A,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2017-02-23 07:50:03.000,experimental,A,NaN,43449
183,UK293,eionetMonitoringSiteCode,RW,General,EEA_13-01-4,2010,2010-01--2010-12,1,2,1.12000,1.0,NaN,NTAXA - Site classifies a heavily modified wat...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,24286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29684,SE728095-175926,euMonitoringSiteCode,LW,"North of Limes norrlandicus, colour>30 mg Pt/l",EEA_11-03-0,2010,2010-06--2010-08,1,1,1.00000,1.0,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,37546
29686,SE728095-175926,euMonitoringSiteCode,LW,2,EEA_123-04-6,2012,2012-06--2012-08,1,1,1.00000,1.0,NaN,NOTE! Aggregation of supportative data are NO...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,37548
29687,SE728095-175926,euMonitoringSiteCode,LW,2,EEA_123-04-6,2011,2011-06--2011-08,1,1,1.04100,1.0,NaN,NOTE! Aggregation of supportative data are NO...,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,37549
29689,SE728095-175926,euMonitoringSiteCode,LW,"North of L. norrlandicus, Water colour>30 mg Pt/l",EEA_11-03-0,2011,2011-06--2011-08,1,1,1.00000,1.0,NaN,"Sampling depth, 0-2m",http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,37551
29722,PL01S1501_1755,euMonitoringSiteCode,RW,12,EEA_13-01-4,2012,2012-03--2012-05,1,1,1.00000,1.0,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,37584

In [138]:
data[data.resultNormalisedEQRValue == 1.0]["resultEQRValue"]

6        1.03719
15       1.08000
40       1.10000
104      1.05900
183      1.12000
          ...
29684    1.00000
29686    1.00000
29687    1.04100
29689    1.00000
29722    1.00000
Name: resultEQRValue, Length: 3749, dtype: float64

In [139]:
data.describe()

,phenomenonTimeReferenceYear,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,UID
count,27245.000000,27245.000000,27245.000000,27245.000000,18848.000000,27245.000000
mean,2012.051239,13.945898,1.753129,0.721350,0.707950,27646.707763
std,2.470338,62.624416,1.410621,0.245548,0.223777,14797.706262
min,1992.000000,1.000000,1.000000,0.000000,-0.053333,29.000000
25%,2010.000000,1.000000,1.000000,0.551003,0.550000,11655.000000
50%,2012.000000,2.000000,1.000000,0.740000,0.710000,32179.000000
75%,2014.000000,3.000000,2.000000,0.908333,0.900125,39660.000000
max,2017.000000,345.000000,22.000000,2.000000,1.000000,47296.000000

In [140]:
data = data[data.resultNormalisedEQRValue >= 0]

In [141]:
data.describe()

,phenomenonTimeReferenceYear,resultEcologicalStatusClassValue,resultNumberOfSamples,resultEQRValue,resultNormalisedEQRValue,UID
count,18846.000000,18846.000000,18846.000000,18846.000000,18846.000000,18846.000000
mean,2011.574605,8.816194,1.741537,0.742750,0.708029,23981.756129
std,2.368949,47.586054,1.403253,0.242068,0.223656,15351.440532
min,1992.000000,1.000000,1.000000,0.000000,0.000000,29.000000
25%,2010.000000,1.000000,1.000000,0.581000,0.550297,6351.250000
50%,2011.000000,2.000000,1.000000,0.785714,0.710000,29770.500000
75%,2013.000000,3.000000,2.000000,0.930000,0.900375,36721.750000
max,2017.000000,345.000000,16.000000,2.000000,1.000000,47296.000000

In [142]:
data.value_counts("resultEcologicalStatusClassValue")

resultEcologicalStatusClassValue
2      6557
1      6198
3      4047
4      1323
345     370
5       351
dtype: int64

In [ ]:
data.to_csv('EQR_clean.csv')