In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Waterbase_v2018_1_WISE4_csv/Waterbase_v2018_1_T_WISE4_BiologyEQRClassificationProcedure.csv") # Read File

In [3]:
data.head()

,CountryCode,observedPropertyDeterminandBiologyEQRCode,parameterWaterBodyCategory,parameterNCSWaterBodyType,parameterWFDIntercalibrationWaterBodyType,parameterNaturalAWBHMWB,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45,procedureBiologicalAnalyticalMethodDescription,resultObservationStatus,Remarks,metadata_versionId,metadata_beginLifeSpanVersion,metadata_statusCode,metadata_observationStatus,metadata_statements,UID
0,AT,EEA_11-04-1,LW,B1,NaN,Natural,0,0.8,0.6,0.4,0.2,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,1
1,AT,EEA_11-04-1,LW,B2,NaN,Natural,0,0.8,0.6,0.4,0.2,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,2
2,AT,EEA_11-04-1,LW,C1a,NaN,Natural,0,0.8,0.6,0.4,0.2,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,3
3,AT,EEA_11-04-1,LW,C1b,NaN,Natural,0,0.8,0.6,0.4,0.2,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,4
4,AT,EEA_11-04-1,LW,D1,NaN,Natural,0,0.8,0.6,0.4,0.2,NaN,NaN,NaN,http://discomap.eea.europa.eu/data/wisesoe/der...,2015-11-30 00:00:00.000,experimental,A,NaN,5

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2553 entries, 0 to 2552
Data columns (total 20 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   CountryCode                                     2553 non-null   object
 1   observedPropertyDeterminandBiologyEQRCode       2553 non-null   object
 2   parameterWaterBodyCategory                      2553 non-null   object
 3   parameterNCSWaterBodyType                       2553 non-null   object
 4   parameterWFDIntercalibrationWaterBodyType       925 non-null    object
 5   parameterNaturalAWBHMWB                         2506 non-null   object
 6   parameterICStatusOfDeterminandBiologyEQR        2553 non-null   int64
 7   parameterBoundaryValueClasses12                 2215 non-null   float64
 8   parameterBoundaryValueClasses23                 2419 non-null   float64
 9   parameterBoundaryValueClasses34                 2412 non-null   float64
 10  parameterBoundaryValueClasses45                 2347 non-null   float64
 11  procedureBiologicalAnalyticalMethodDescription  1901 non-null   object
 12  resultObservationStatus                         583 non-null    object
 13  Remarks                                         569 non-null    object
 14  metadata_versionId                              2553 non-null   object
 15  metadata_beginLifeSpanVersion                   2553 non-null   object
 16  metadata_statusCode                             2553 non-null   object
 17  metadata_observationStatus                      2553 non-null   object
 18  metadata_statements                             0 non-null      float64
 19  UID                                             2553 non-null   int64
dtypes: float64(5), int64(2), object(13)
memory usage: 399.0+ KB

In [5]:
data["parameterWaterBodyCategory"].unique()

array(['LW', 'RW'], dtype=object)

In [6]:
# Divide the citeria into 2 categories 

data_LW = data[data["parameterWaterBodyCategory"] == "LW"]  # LW 
data_RW = data[data["parameterWaterBodyCategory"] == "RW"]  # RW

In [7]:
# Group the country code together

data_LW = data_LW.groupby(["CountryCode"]).mean()
data_RW = data_RW.groupby(["CountryCode"]).mean()

In [8]:
# Check the Value in each Dataset

data_LW

,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45,metadata_statements,UID
CountryCode,,,,,,,
AT,0.555556,0.800000,0.600000,0.400000,0.200000,NaN,2403.444444
BE,0.125000,NaN,0.600000,0.400000,0.200000,NaN,1095.125000
BG,0.000000,0.796533,0.599667,0.411733,0.253067,NaN,2219.866667
CY,1.000000,NaN,0.600000,NaN,NaN,NaN,3675.000000
EE,0.875000,0.636000,0.386000,0.276000,0.196000,NaN,1491.000000
ES,0.000000,NaN,NaN,NaN,NaN,NaN,1224.096154
FI,0.000000,0.800000,0.600000,0.400000,0.200000,NaN,574.000000
GB,0.840909,0.830513,0.626667,0.409487,0.236923,NaN,3461.931818
HR,0.000000,0.818750,0.618750,0.418750,0.218750,NaN,5174.187500
IE,1.000000,0.804000,0.603200,0.400800,0.205200,NaN,4889.040000
LT,0.666667,0.743333,0.480000,0.266667,0.096667,NaN,3576.333333
LV,1.000000,0.805000,0.605000,0.405000,0.200000,NaN,5182.000000
NL,0.000000,0.800000,0.548137,0.365318,0.182957,NaN,4400.284314
PL,0.972973,0.743243,0.507297,0.306014,0.138514,NaN,3052.959459
PT,0.500000,NaN,0.190000,NaN,NaN,NaN,459.500000
RO,0.000000,0.774118,0.571765,0.385882,0.250000,NaN,2299.352941
SE,0.285714,0.712653,0.507959,0.386531,0.100000,NaN,3594.897959
SI,0.666667,0.800000,0.600000,0.400000,0.200000,NaN,3674.000000

In [9]:
# Check the Value in each Dataset

data_RW

,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45,metadata_statements,UID
CountryCode,,,,,,,
AT,0.000000,0.817097,0.600968,0.418710,0.237742,NaN,300.854839
BE,0.717791,0.964214,0.704029,0.471145,0.277648,NaN,1962.026585
BG,0.241379,0.817379,0.634069,0.413345,0.260966,NaN,3737.275862
CH,0.000000,NaN,NaN,NaN,NaN,NaN,214.500000
CY,1.000000,0.963000,0.722214,0.482357,0.242429,NaN,2553.857143
DE,1.000000,0.765000,0.575000,0.413333,0.176667,NaN,1368.500000
EE,0.846154,0.850000,0.654545,0.520000,0.340000,NaN,2481.769231
ES,0.106557,0.863333,0.649048,0.431746,0.217460,NaN,2948.040984
FI,0.736842,0.800000,0.600000,0.400000,0.200000,NaN,850.052632
FR,0.000000,0.935577,0.788305,0.549870,0.295868,NaN,2013.000000
GB,0.611650,0.913824,0.778480,0.615911,0.456453,NaN,2300.587379
HR,0.000000,0.800000,0.600000,0.400000,0.200000,NaN,4854.750000
IE,1.000000,0.850000,0.750000,0.650000,0.450000,NaN,3802.689655
IT,0.400000,0.906701,0.704000,0.531100,0.291900,NaN,1115.270000
LT,0.500000,0.697500,0.537500,0.370000,0.225000,NaN,3638.300000
LU,1.000000,0.972800,0.754000,0.520400,0.303600,NaN,3268.500000
LV,0.454545,0.912000,0.702000,0.412000,0.248000,NaN,3630.454545
NL,0.000000,0.800000,0.428659,0.286341,0.145244,NaN,4553.500000
NO,1.000000,0.961429,0.830000,0.550000,0.270000,NaN,564.000000
PL,0.994012,0.755503,0.574281,0.376257,0.185928,NaN,3387.000000
PT,0.157895,0.910526,0.675263,0.450526,0.224737,NaN,770.842105
RO,0.625000,0.725500,0.543000,0.381579,0.200000,NaN,2464.025000
SE,0.888889,0.825556,0.642222,0.435556,0.271250,NaN,3206.333333
SI,0.301587,0.800000,0.600000,0.400000,0.200000,NaN,3220.904762
SK,0.800000,0.841600,0.641733,0.441867,0.242000,NaN,3705.573333

In [10]:
# The value that we are going to keep from this dataset are these following column

# 1. parameterICStatusOfDeterminandBiologyEQR (Flag indicating whether the biological determinand has been intercalibrated)
# 2. parameterBoundaryValueClasses12 (Boundary between high and good EQR)
# 3. parameterBoundaryValueClasses23 (Boundary between good and moderate EQR)
# 4. parameterBoundaryValueClasses34 (Boundary between moderate and poor EQR)
# 5. parameterBoundaryValueClasses45 (Boundary between poor and bad EQR)

data_LW = data_LW[["parameterICStatusOfDeterminandBiologyEQR","parameterBoundaryValueClasses12","parameterBoundaryValueClasses23","parameterBoundaryValueClasses34","parameterBoundaryValueClasses45"]]
data_RW = data_RW[["parameterICStatusOfDeterminandBiologyEQR","parameterBoundaryValueClasses12","parameterBoundaryValueClasses23","parameterBoundaryValueClasses34","parameterBoundaryValueClasses45"]]

In [11]:
# Reset Indexes
data_LW = data_LW.reset_index()
data_RW = data_RW.reset_index()

In [12]:
# Fill the missing Value
# First, Focusing on data_LW dataset
data_LW

,CountryCode,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45
0,AT,0.555556,0.800000,0.600000,0.400000,0.200000
1,BE,0.125000,NaN,0.600000,0.400000,0.200000
2,BG,0.000000,0.796533,0.599667,0.411733,0.253067
3,CY,1.000000,NaN,0.600000,NaN,NaN
4,EE,0.875000,0.636000,0.386000,0.276000,0.196000
5,ES,0.000000,NaN,NaN,NaN,NaN
6,FI,0.000000,0.800000,0.600000,0.400000,0.200000
7,GB,0.840909,0.830513,0.626667,0.409487,0.236923
8,HR,0.000000,0.818750,0.618750,0.418750,0.218750
9,IE,1.000000,0.804000,0.603200,0.400800,0.205200
10,LT,0.666667,0.743333,0.480000,0.266667,0.096667
11,LV,1.000000,0.805000,0.605000,0.405000,0.200000
12,NL,0.000000,0.800000,0.548137,0.365318,0.182957
13,PL,0.972973,0.743243,0.507297,0.306014,0.138514
14,PT,0.500000,NaN,0.190000,NaN,NaN
15,RO,0.000000,0.774118,0.571765,0.385882,0.250000
16,SE,0.285714,0.712653,0.507959,0.386531,0.100000
17,SI,0.666667,0.800000,0.600000,0.400000,0.200000

In [13]:
# BE and CY rows has a missing parameterBoundayValueClasses12 but the overall data look really similar to AT, FI and SI. Therefore, in this case the value will be filled by using parameterBoundayValueClasses12 of other column
data_LW.iloc[[0,1,3,6,17],1:]

,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45
0,0.555556,0.8,0.6,0.4,0.2
1,0.125000,NaN,0.6,0.4,0.2
3,1.000000,NaN,0.6,NaN,NaN
6,0.000000,0.8,0.6,0.4,0.2
17,0.666667,0.8,0.6,0.4,0.2

In [14]:
# BE and CY rows has a missing parameterBoundayValueClasses12 but the overall data look really similar to AT, FI and SI. Therefore, in this case the value will be filled by using parameterBoundayValueClasses12 of other column
data_LW.iloc[1,1:] = data_LW.iloc[0,1:] # Set BE = AT
data_LW.iloc[3,1:] = data_LW.iloc[0,1:] # Set BE = AT

In [15]:
data_LW

,CountryCode,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45
0,AT,0.555556,0.800000,0.600000,0.400000,0.200000
1,BE,0.555556,0.800000,0.600000,0.400000,0.200000
2,BG,0.000000,0.796533,0.599667,0.411733,0.253067
3,CY,0.555556,0.800000,0.600000,0.400000,0.200000
4,EE,0.875000,0.636000,0.386000,0.276000,0.196000
5,ES,0.000000,NaN,NaN,NaN,NaN
6,FI,0.000000,0.800000,0.600000,0.400000,0.200000
7,GB,0.840909,0.830513,0.626667,0.409487,0.236923
8,HR,0.000000,0.818750,0.618750,0.418750,0.218750
9,IE,1.000000,0.804000,0.603200,0.400800,0.205200
10,LT,0.666667,0.743333,0.480000,0.266667,0.096667
11,LV,1.000000,0.805000,0.605000,0.405000,0.200000
12,NL,0.000000,0.800000,0.548137,0.365318,0.182957
13,PL,0.972973,0.743243,0.507297,0.306014,0.138514
14,PT,0.500000,NaN,0.190000,NaN,NaN
15,RO,0.000000,0.774118,0.571765,0.385882,0.250000
16,SE,0.285714,0.712653,0.507959,0.386531,0.100000
17,SI,0.666667,0.800000,0.600000,0.400000,0.200000

In [16]:
# By checking the EQR_clean dataset we gain an information that there is no parameterWaterBodyCategory in ES and PT country that contain LW type of water on it therefore, we can drop these rows
data_LW = data_LW.drop(labels=[5,14], axis=0)

In [17]:
data_LW

,CountryCode,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45
0,AT,0.555556,0.800000,0.600000,0.400000,0.200000
1,BE,0.555556,0.800000,0.600000,0.400000,0.200000
2,BG,0.000000,0.796533,0.599667,0.411733,0.253067
3,CY,0.555556,0.800000,0.600000,0.400000,0.200000
4,EE,0.875000,0.636000,0.386000,0.276000,0.196000
6,FI,0.000000,0.800000,0.600000,0.400000,0.200000
7,GB,0.840909,0.830513,0.626667,0.409487,0.236923
8,HR,0.000000,0.818750,0.618750,0.418750,0.218750
9,IE,1.000000,0.804000,0.603200,0.400800,0.205200
10,LT,0.666667,0.743333,0.480000,0.266667,0.096667
11,LV,1.000000,0.805000,0.605000,0.405000,0.200000
12,NL,0.000000,0.800000,0.548137,0.365318,0.182957
13,PL,0.972973,0.743243,0.507297,0.306014,0.138514
15,RO,0.000000,0.774118,0.571765,0.385882,0.250000
16,SE,0.285714,0.712653,0.507959,0.386531,0.100000
17,SI,0.666667,0.800000,0.600000,0.400000,0.200000

In [18]:
# Second, Focusing on data_RW dataset
data_RW

,CountryCode,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45
0,AT,0.000000,0.817097,0.600968,0.418710,0.237742
1,BE,0.717791,0.964214,0.704029,0.471145,0.277648
2,BG,0.241379,0.817379,0.634069,0.413345,0.260966
3,CH,0.000000,NaN,NaN,NaN,NaN
4,CY,1.000000,0.963000,0.722214,0.482357,0.242429
5,DE,1.000000,0.765000,0.575000,0.413333,0.176667
6,EE,0.846154,0.850000,0.654545,0.520000,0.340000
7,ES,0.106557,0.863333,0.649048,0.431746,0.217460
8,FI,0.736842,0.800000,0.600000,0.400000,0.200000
9,FR,0.000000,0.935577,0.788305,0.549870,0.295868
10,GB,0.611650,0.913824,0.778480,0.615911,0.456453
11,HR,0.000000,0.800000,0.600000,0.400000,0.200000
12,IE,1.000000,0.850000,0.750000,0.650000,0.450000
13,IT,0.400000,0.906701,0.704000,0.531100,0.291900
14,LT,0.500000,0.697500,0.537500,0.370000,0.225000
15,LU,1.000000,0.972800,0.754000,0.520400,0.303600
16,LV,0.454545,0.912000,0.702000,0.412000,0.248000
17,NL,0.000000,0.800000,0.428659,0.286341,0.145244
18,NO,1.000000,0.961429,0.830000,0.550000,0.270000
19,PL,0.994012,0.755503,0.574281,0.376257,0.185928
20,PT,0.157895,0.910526,0.675263,0.450526,0.224737
21,RO,0.625000,0.725500,0.543000,0.381579,0.200000
22,SE,0.888889,0.825556,0.642222,0.435556,0.271250
23,SI,0.301587,0.800000,0.600000,0.400000,0.200000
24,SK,0.800000,0.841600,0.641733,0.441867,0.242000

In [19]:
# For this dataset the only rows that contain is CH but we have no data that contain CH country code on the EQR_clean dataset Therefore we can drop this dataset

data_RW = data_RW.drop(labels=3, axis=0)

In [20]:
data_RW

,CountryCode,parameterICStatusOfDeterminandBiologyEQR,parameterBoundaryValueClasses12,parameterBoundaryValueClasses23,parameterBoundaryValueClasses34,parameterBoundaryValueClasses45
0,AT,0.000000,0.817097,0.600968,0.418710,0.237742
1,BE,0.717791,0.964214,0.704029,0.471145,0.277648
2,BG,0.241379,0.817379,0.634069,0.413345,0.260966
4,CY,1.000000,0.963000,0.722214,0.482357,0.242429
5,DE,1.000000,0.765000,0.575000,0.413333,0.176667
6,EE,0.846154,0.850000,0.654545,0.520000,0.340000
7,ES,0.106557,0.863333,0.649048,0.431746,0.217460
8,FI,0.736842,0.800000,0.600000,0.400000,0.200000
9,FR,0.000000,0.935577,0.788305,0.549870,0.295868
10,GB,0.611650,0.913824,0.778480,0.615911,0.456453
11,HR,0.000000,0.800000,0.600000,0.400000,0.200000
12,IE,1.000000,0.850000,0.750000,0.650000,0.450000
13,IT,0.400000,0.906701,0.704000,0.531100,0.291900
14,LT,0.500000,0.697500,0.537500,0.370000,0.225000
15,LU,1.000000,0.972800,0.754000,0.520400,0.303600
16,LV,0.454545,0.912000,0.702000,0.412000,0.248000
17,NL,0.000000,0.800000,0.428659,0.286341,0.145244
18,NO,1.000000,0.961429,0.830000,0.550000,0.270000
19,PL,0.994012,0.755503,0.574281,0.376257,0.185928
20,PT,0.157895,0.910526,0.675263,0.450526,0.224737
21,RO,0.625000,0.725500,0.543000,0.381579,0.200000
22,SE,0.888889,0.825556,0.642222,0.435556,0.271250
23,SI,0.301587,0.800000,0.600000,0.400000,0.200000
24,SK,0.800000,0.841600,0.641733,0.441867,0.242000

In [21]:
# Export these dataset

data_LW.to_csv("EQR_LW_Criteria.csv",index=False)
data_RW.to_csv("EQR_RW_Criteria.csv",index=False)